services:
  - type: web
    name: tetris-multiplayer
    env: node
    buildCommand: npm install && npm run build
    startCommand: node src/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free
